package org.iatevale.example.vertextai.common;

import com.google.cloud.vertexai.VertexAI;
import com.google.cloud.vertexai.api.Candidate;
import org.iatevale.config.GCloudAuthParameters;
import org.iatevale.config.IATevaleConfig;

import java.io.IOException;
import java.util.List;

public class VertextaiUtil {

    static public VertexAI.Builder vertexBuilder() throws IOException {
        final GCloudAuthParameters parameters = IATevaleConfig.getGCloudAuthParameters();
        return new VertexAI.Builder()
                .setProjectId(parameters.projectId())
                .setCredentials(parameters.credentials());
    }

    static public void displayCandidate(List<Candidate> candidates) {
        if (!candidates.isEmpty()) {
            for (int i = 0; i < candidates.size(); i++) {
                System.out.println("[Candidate " + (i + 1) + "]");
                displayCandidate(candidates.get(i));
            }
        } else {
            System.out.println("No candidates were generated by the model.");
        }

    }
    
    static public void displayCandidate(Candidate candidate) {
        System.out.println(candidate.getContent());
    }

}
