load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

java_library(
    name = "timer",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
    ],
)
